### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by ArnaudPrigent** [Arianee/ArianeeMaster#11]
Suite au premier atelier:

Dashboard public
- Nombre de certificat au total
- Graph des émissions de certificats
- Graph des transferts
- identités des marques référencées
- nombre de wallet avec un certificat au moins
- volume de transaction sur le réseau
- prix aria
- afficher les blocks

- liste des dernières transactions (transfert certif N°12345 de 0xdsldjsq à 0xdsqdsqlj le DATE) dans le block 234567

testnet/mainnet
echelle de temps

Dashboard interne / Back office général
stats
- reprise du dashboard public
- nombre de POA dispo dans le faucet
- identité en attente

BO
- Démarrer la valider d'une identité en multisig
- Preview de l'identité
- liste de l'ensemble des BDH / version du bdh

**Comment by gnarco** [comment]
First iteration :

- Find a nice data framework
- Put on a dedicated firebase project
- Total certificates issued
- Total verified identity
- Chart with issued certificate over time
- Chart with transaction number (proof / transfer / ...)

**Comment by TimotheDavid** [comment]
Hello I am really intersting by the project : it's my stack and what I would like to do ... can we discuss ?
