### ISSUE TITLE
Check in package-lock.json

### ISSUE THREAD

**Issue by fulldecent** [Arianee/ArianeeMaster#3]
The resolved file package-lock.json should be checked into the repository. This allows the test cases to be repeatable.

Reference on best practice: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by mvaullerin** [comment]
Fixed in : https://github.com/Arianee/ArianeeMaster/commit/31d7ba8ad882fb1101eac06810bb36b7d88f2c99
