### ISSUE TITLE
Update ArianeeStaking reference

### ISSUE THREAD

**Issue by fulldecent** [Arianee/ArianeeMaster#4]
The ArianeeStaking submodule is currently referencing commit 2965f7b. That commit is not publicly available (did you forget to check it in?)

Recommendation: update to the master commit or check in the missing commit.

**Comment by mvaullerin** [comment]
Solved in : https://github.com/Arianee/ArianeeMaster/commit/346d90cb4f1d46afff581dd0e199935ac89b3caf
