### ISSUE TITLE
[Digital Asset] Modify few things

### ISSUE THREAD

**Issue by camzahr** [Arianee/ArianeeMaster#57]
1/ Modify Text on the collections :
- If NFT.Type == Digital Asset, then show "{Number} NFT"
- Else, If NFT.Type == Digital Twins, then show "{Number} Article"

**Comment by Bigdzif** [comment]
> 

const connectWallet = async () => {
  if (typeof window.NFT.Type !== "undefined") {
    let provider = window.NFT;
    // edge case if MM and CBW are both installed
    if (windowNFT.Type.providers?.length) {
      windowNFT.Type.providers.forEach(async (p) => {
        if (p.isMetaMask) provider = p;
      });
    }
    await provider.request({
      method: "eth_requestAccounts",
      params: [],
    });
  }
};
